<!doctype html public "-//w3c//dtd html 4.01 transitional//en">
<html>
	<head>
		<title><?= $title ?></title>
		<meta http-equiv="content-type" content="text/html; charset=utf-8" />
		<meta name="developer" content="Roughdot.nl - Webdesign & Development" />
		<script language="JavaScript" src="includes/xms.js"></script>
		<link href="includes/xms.css" rel="stylesheet" type="text/css" />
		<script language="JavaScript" type="text/javascript">
			<!--
				if(top.opener == null) {
					window.close();
				}
			// -->
		</script>
		<!--
			  TECHNISCHE REALISATIE:
			  Roughdot Web Design & Development
			  http://www.roughdot.nl/
			-->
	</head>
	<body>
		<iframe id="RPC" name="RPC" style="width:0px; height:0px; border-width:0px;" src=""></iframe>
		<?= $content ?>
	</body>
</html>