<!doctype html public "-//w3c//dtd html 4.01 transitional//en">
<html>
	<head>
		<title>RPC</title>
		<meta http-equiv="content-type" content="text/html; charset=utf-8" />
		<meta name="developer" content="Roughdot.nl - Webdesign & Development" />
		<script language="JavaScript" src="includes/xms.js"></script>
		<script language="JavaScript" type="text/javascript">
			<!--
				if(window.parent == window) {
					// if the window is not opened by another window, it is to be closed
					window.close();
				}
			// -->
		</script>
		<!--
			  TECHNISCHE REALISATIE:
			  Roughdot Web Design & Development
			  http://www.roughdot.nl/
			-->
	</head>
	<body>
		<?= $content ?>
	</body>
</html>